version: '3.8'
services:
  frontend:
    image: naofeleal/motus_ihm:latest
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    image: naofeleal/motus_api:latest
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: naofeleal/motus_db:latest
    ports:
      - "5432:5432"
